### ISSUE TITLE
Export PkgConfig file for Windows.

### ISSUE THREAD

**Issue by seanyen** [conda-forge/urdfdom-feedstock#2]
This is a feature request to enable `.pc` file to be exported on Windows, so downstream project can consume it.

**Comment by seanyen** [comment]
https://github.com/conda-forge/staged-recipes/pull/9968

**Comment by traversaro** [comment]
I want to work on this, but first I will ensure that the latest version of urdfdom is available.

**Comment by traversaro** [comment]
Upstream PRs:
* https://github.com/ros/console_bridge/pull/96
* https://github.com/ros/urdfdom_headers/pull/72
* https://github.com/ros/urdfdom/pull/169

conda-forge PRs:
* https://github.com/conda-forge/console_bridge-feedstock/pull/11
